import type { ExpertiseGroup } from "./types";

export const expertiseGroups: readonly ExpertiseGroup[] = [
  {
    title: "Commerce Platforms",
    skills: [
      "Shopify Plus",
      "Shopify Hydrogen",
      "Shopify Oxygen",
      "Online Store 2.0",
      "Shopify Markets",
      "WooCommerce",
      "WordPress",
      "Headless Commerce",
    ],
  },
  {
    title: "Shopify Engineering",
    skills: [
      "Liquid",
      "Storefront API",
      "GraphQL Admin API",
      "Customer Account API",
      "Shopify Functions",
      "Checkout UI Extensions",
      "Shopify CLI",
      "Bulk Operations",
      "Webhooks",
      "Metafields",
      "Metaobjects",
    ],
  },
  {
    title: "Front-End Engineering",
    skills: [
      "React",
      "TypeScript",
      "React Router",
      "JavaScript",
      "HTML5",
      "CSS3",
      "Responsive Design",
      "Streaming SSR",
      "Component Systems",
      "Accessibility",
    ],
  },
  {
    title: "Backend and Data",
    skills: [
      "Node.js",
      "Express.js",
      "PHP",
      "Ruby on Rails",
      "GraphQL",
      "REST APIs",
      "PostgreSQL",
      "MySQL",
      "Redis",
      "Background Jobs",
      "Authentication",
      "Caching",
    ],
  },
  {
    title: "Enterprise Integrations",
    skills: [
      "ERP Integration",
      "PIM Integration",
      "CRM Integration",
      "NetSuite",
      "Oracle",
      "Payment Systems",
      "Fulfillment Systems",
      "Inventory Systems",
      "Order Management",
      "Third-Party APIs",
    ],
  },
  {
    title: "Cloud, Quality, and Delivery",
    skills: [
      "AWS",
      "Docker",
      "GitHub Actions",
      "CI/CD",
      "Playwright",
      "Vitest",
      "Automated Testing",
      "Application Monitoring",
      "Incident Response",
      "Production Support",
    ],
  },
  {
    title: "Performance, Analytics, and Growth",
    skills: [
      "Core Web Vitals",
      "Web Performance",
      "Technical SEO",
      "Structured Data",
      "WCAG Accessibility",
      "Google Analytics 4",
      "Google Tag Manager",
      "Conversion Optimization",
      "A/B Testing",
    ],
  },
];
